# Kentucky School Initial Data Review

The goal for this project is to see if there is a correlation between absenteeism and dropout rate. I've decided first to look at the absenteeism data from 2024-2025 and then I will continue on and look at the dropout rate.

Libraries and Parameters

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn

seaborn.set_theme(style='whitegrid')

## Chronic Absenteeism Dataset (2024-2025)

In [13]:
absent_2324_df = pd.read_csv("../Dataset/KYRC24_CRDC_Chronic_Absenteeism.csv")

## Initial Dataset Review

In [22]:
absent_2324_df

,School Year,Collected School Year,County Number,County Name,District Number,District Name,School Number,School Name,School Code,State School Id,NCES ID,CO-OP,CO-OP Code,School Type,Demographic,Total,Female,Male
0,20232024,2020-2021,1,ADAIR,1,Adair County,10,Adair County High School,1010,1001010,210003000001,GRREC,902,A1,Total Student Count,783,349.0,434.0
1,20232024,2020-2021,1,ADAIR,1,Adair County,10,Adair County High School,1010,1001010,210003000001,GRREC,902,A1,African American,11,6.0,5.0
2,20232024,2020-2021,1,ADAIR,1,Adair County,10,Adair County High School,1010,1001010,210003000001,GRREC,902,A1,American Indian or Alaska Native,3,1.0,2.0
3,20232024,2020-2021,1,ADAIR,1,Adair County,10,Adair County High School,1010,1001010,210003000001,GRREC,902,A1,Asian,1,NaN,1.0
4,20232024,2020-2021,1,ADAIR,1,Adair County,10,Adair County High School,1010,1001010,210003000001,GRREC,902,A1,Hispanic or Latino,40,14.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7538,20232024,2020-2021,11,BOYLE,603,Kentucky School for the Deaf,390,Kentucky School for the Deaf,603390,11603390,210009501715,CKEC,901,D1,Hispanic or Latino,6,1.0,5.0
7539,20232024,2020-2021,11,BOYLE,603,Kentucky School for the Deaf,390,Kentucky School for the Deaf,603390,11603390,210009501715,CKEC,901,D1,Two or More Races,3,1.0,2.0
7540,20232024,2020-2021,11,BOYLE,603,Kentucky School for the Deaf,390,Kentucky School for the Deaf,603390,11603390,210009501715,CKEC,901,D1,White (non-Hispanic),59,25.0,34.0
7541,20232024,2020-2021,11,BOYLE,603,Kentucky School for the Deaf,390,Kentucky School for the Deaf,603390,11603390,210009501715,CKEC,901,D1,Students with Disabilities (IEP),7,3.0,4.0
7542,20232024,2020-2021,11,BOYLE,603,Kentucky School for the Deaf,390,Kentucky School for the Deaf,603390,11603390,210009501715,CKEC,901,D1,English Learner,2,NaN,2.0

## Analyzing the Data

In [23]:
absent_2324_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7543 entries, 0 to 7542
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   School Year            7543 non-null   int64
 1   Collected School Year  7543 non-null   object
 2   County Number          7543 non-null   int64
 3   County Name            7543 non-null   object
 4   District Number        7543 non-null   int64
 5   District Name          7543 non-null   object
 6   School Number          7543 non-null   int64
 7   School Name            7543 non-null   object
 8   School Code            7543 non-null   int64
 9   State School Id        7543 non-null   int64
 10  NCES ID                7543 non-null   int64
 11  CO-OP                  7543 non-null   object
 12  CO-OP Code             7543 non-null   int64
 13  School Type            7543 non-null   object
 14  Demographic            7543 non-null   object
 15  Total                  7543 non-null   int64
 16  Female                 6505 non-null   float64
 17  Male                   6814 non-null   float64
dtypes: float64(2), int64(9), object(7)
memory usage: 1.0+ MB

In [24]:
absent_2324_df.columns = absent_2324_df.columns.str.strip()

## Data Cleanup

In [25]:
school_df = absent_2324_df[absent_2324_df["Demographic"] != "Total Student Count"]
school_df.sort_values(by="Total",ascending=False).head(10)

,School Year,Collected School Year,County Number,County Name,District Number,District Name,School Number,School Name,School Code,State School Id,NCES ID,CO-OP,CO-OP Code,School Type,Demographic,Total,Female,Male
500,20232024,2020-2021,8,BOONE,35,Boone County,71,Larry A. Ryle High School,35071,8035071,210051000011,NKCES,905,A1,White (non-Hispanic),1388,659.0,729.0
6026,20232024,2020-2021,93,OLDHAM,465,Oldham County,60,Oldham County High School,465060,93465060,210453001125,OVEC,906,A1,White (non-Hispanic),1288,609.0,679.0
3145,20232024,2020-2021,51,HENDERSON,251,Henderson County,60,Henderson County High School,251060,51251060,210271000577,WKEC,908,A1,White (non-Hispanic),1215,557.0,658.0
3863,20232024,2020-2021,56,JEFFERSON,275,Jefferson County,105,Ballard High,275105,56275105,210299000695,GREC,909,A1,White (non-Hispanic),1062,560.0,502.0
2732,20232024,2020-2021,43,GRAYSON,211,Grayson County,85,Grayson County High School,211085,43211085,210230000486,GRREC,902,A1,White (non-Hispanic),1057,463.0,594.0
4161,20232024,2020-2021,56,JEFFERSON,275,Jefferson County,200,duPont Manual High,275200,56275200,210299000734,GREC,909,A1,White (non-Hispanic),1041,593.0,448.0
409,20232024,2020-2021,8,BOONE,35,Boone County,15,Randall K. Cooper High School,35015,8035015,210051002206,NKCES,905,A1,White (non-Hispanic),976,450.0,526.0
4105,20232024,2020-2021,56,JEFFERSON,275,Jefferson County,179,Central High Magnet Career Academy,275179,56275179,210299000730,GREC,909,A1,African American,931,660.0,271.0
5135,20232024,2020-2021,71,LOGAN,351,Logan County,140,Logan County High School,351140,71351140,210354001458,GRREC,902,A1,White (non-Hispanic),917,459.0,458.0
3677,20232024,2020-2021,56,JEFFERSON,275,Jefferson County,75,Pleasure Ridge Park High,275075,56275075,210299000668,GREC,909,A1,White (non-Hispanic),893,432.0,461.0

Removing Total Student Count to avoid skewing the dataset

In [18]:
gender_school_df = school_df[['Female', 'Male']].sum()
gender_school_df

Female    117221.0
Male      134317.0
dtype: float64

In [19]:
school_df.isna().sum()

sorted_school_df = school_df.sort_values(by="Total", ascending=False)

In [20]:
county_large_df = sorted_school_df.groupby("County Name")["Total"].sum().sort_values(ascending=False).head(10) 
county_large_df

County Name
JEFFERSON    74165
FAYETTE      17277
BOONE         8632
WARREN        7742
DAVIESS       7045
OLDHAM        6175
KENTON        6011
HENDERSON     4407
BELL          3678
PULASKI       3338
Name: Total, dtype: int64

## Visual Analysis and Discovery